# Generated by Django 2.2.4 on 2020-11-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mycar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_company', models.TextField(blank=True, max_length=100, null=True)),
                ('car_name', models.TextField(blank=True, max_length=100, null=True)),
                ('car_old', models.TextField(blank=True, max_length=100, null=True)),
                ('car_oil', models.TextField(blank=True, max_length=100, null=True)),
                ('car_number', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
