# Generated by Django 2.2.4 on 2020-11-03 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycar',
            old_name='car_company',
            new_name='carCompany',
        ),
        migrations.RenameField(
            model_name='mycar',
            old_name='car_name',
            new_name='carName',
        ),
        migrations.RenameField(
            model_name='mycar',
            old_name='car_number',
            new_name='carNumber',
        ),
        migrations.RenameField(
            model_name='mycar',
            old_name='car_oil',
            new_name='carOil',
        ),
        migrations.RenameField(
            model_name='mycar',
            old_name='car_old',
            new_name='carOld',
        ),
    ]
