# Generated by Django 2.2.4 on 2020-11-03 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201103_1327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mycar',
        ),
    ]
