# Generated by Django 3.1.3 on 2020-11-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mycar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=255)),
                ('car_company', models.CharField(blank=True, max_length=100, null=True)),
                ('car_name', models.CharField(blank=True, max_length=100, null=True)),
                ('car_old', models.IntegerField(blank=True, null=True)),
                ('car_oil', models.CharField(blank=True, choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Gas', 'Gas')], max_length=100, null=True)),
                ('car_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
