# Generated by Django 3.1.3 on 2020-11-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycar',
            name='car_oil',
            field=models.CharField(blank=True, choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Gas', 'Gas')], max_length=100, null=True),
        ),
    ]
