# Generated by Django 3.1.3 on 2020-11-03 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0002_mycar_car_oil'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycar',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
