# Generated by Django 3.1.3 on 2020-11-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0003_mycar_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
