# Generated by Django 3.1.3 on 2020-11-03 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0004_auto_20201103_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycar',
            name='created_at',
        ),
    ]
