# Generated by Django 3.1.3 on 2020-11-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnginOil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=255)),
                ('change_date', models.DateField()),
                ('enginoil_img', models.ImageField(blank=True, upload_to='enginoil/img')),
                ('center', models.CharField(max_length=100)),
                ('change_km', models.IntegerField()),
            ],
        ),
    ]
