# Generated by Django 3.1.3 on 2020-11-04 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enginoil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enginoil',
            old_name='change_data',
            new_name='change_date',
        ),
    ]
